---
config:
  layout: dagre
---
flowchart TB
    Start(["Kezdés"]) --> Profile[/"Profil fül megnyitása"/]
    Profile --> MyCamping[/"Saját kemping menüpont"/]
    CampingView[/"Kemping áttekintés oldal"/] --> AddSpotButton[/"Hely hozzáadása<br>gomb megnyomása"/]
    AddSpotButton --> SpotName[/"Hely neve megadása"/]
    SpotName --> SpotType[/"Típus megadása:<br>tóparti, erdei, stb."/]
    SpotType --> Capacity[/"Maximum befogadó képesség"/]
    Capacity --> Price[/"Ár/éjszaka megadása"/]
    Price --> Description[/"Leírás megadása"/]
    Description --> ValidateSpot{"Hely adatok<br>validálása"}
    ValidateSpot -- Sikertelen --> ErrorValidate[/"Hiba: Hiányzó vagy<br>érvénytelen adat"/]
    ValidateSpot -- Sikeres --> Success[/"Kempinghely sikeresen<br>hozzáadva!"/]
    ErrorValidate --> SpotName
    Success --> UpdateView[/"Kemping áttekintés<br>frissítése"/]
    UpdateView --> AddMore{"További helyehozzáadása?"}
    AddMore -- Igen --> AddSpotButton
    AddMore -- Nem --> End(["Vége"])
    MyCamping --> CampingView
