CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" varchar,
  "is_superuser" boolean DEFAULT false,
  "phone_number" varchar
);

CREATE TABLE "user_guest" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "birth_date" date,
  "place_of_birth" varchar,
  "gender" varchar,
  "citizenship" varchar,
  "mothers_birth_name" varchar,
  "ID" varchar,
  "passport_number" varchar,
  "visa" varchar,
  "resident_permit_number" varchar,
  "date_of_entry" date,
  "place_of_entry" varchar
);

CREATE TABLE "location" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postcode" int,
  "county" varchar,
  "city" varchar,
  "street" varchar,
  "street_number" varchar
);

CREATE TABLE "camping" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "camping_name" varchar NOT NULL,
  "owner_first_name" varchar,
  "owner_last_name" varchar,
  "location_id" int NOT NULL,
  "description" text,
  "company_name" varchar,
  "tax_id" varchar,
  "billing_address" varchar
);

CREATE TABLE "booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "camping_id" int NOT NULL,
  "camping_spot_id" int NOT NULL,
  "arrival_date" date NOT NULL,
  "departure_date" date NOT NULL,
  "status" varchar,
  "qr_code" varchar
);

CREATE TABLE "camping_spot" (
  "spot_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "name" varchar,
  "type" varchar,
  "capacity" int,
  "price_per_night" int,
  "is_available" boolean DEFAULT true,
  "description" text,
  "updated_at" datetime,
  "row" int,
  "column" int,
  "rating" float,
  "tags" varchar
);

CREATE TABLE "camping_photo" (
  "photo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "photo_url" varchar NOT NULL,
  "caption" varchar,
  "uploaded_at" date
);

CREATE TABLE "entrance_gate" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "timestamp" datetime,
  "gate_id" int,
  "opening_time" time,
  "closing_time" time
);

CREATE TABLE "comment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "user_id" int NOT NULL,
  "parent_id" int,
  "rating" int,
  "comment" text,
  "upload_date" date
);

ALTER TABLE "user_guest" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "camping" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "camping" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("camping_spot_id") REFERENCES "camping_spot" ("spot_id");

ALTER TABLE "camping_spot" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "camping_photo" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "entrance_gate" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("parent_id") REFERENCES "comment" ("id");
