CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(150) UNIQUE NOT NULL,
  "password" varchar(150) NOT NULL,
  "role" boolean DEFAULT false,
  "is_superuser" boolean DEFAULT false,
  "phone_number" varchar(15)
);

CREATE TABLE "user_guest" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "birth_date" date,
  "place_of_birth" varchar(100),
  "gender" varchar(20),
  "citizenship" varchar(100),
  "mothers_birth_name" varchar(100),
  "id_card_number" varchar(30),
  "passport_number" varchar(30),
  "visa" varchar(50),
  "resident_permit_number" varchar(50),
  "date_of_entry" date,
  "place_of_entry" varchar(100)
);

CREATE TABLE "location" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postcode" int,
  "county" varchar(100),
  "city" varchar(100),
  "street" varchar(100),
  "street_number" varchar(10)
);

CREATE TABLE "camping" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "camping_name" varchar(200) NOT NULL,
  "owner_first_name" varchar(100),
  "owner_last_name" varchar(100),
  "location_id" int NOT NULL,
  "description" text,
  "company_name" varchar(150),
  "tax_id" varchar(15),
  "billing_address" varchar(255)
);

CREATE TABLE "camping_tag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "tag" varchar(50) NOT NULL
);

CREATE TABLE "camping_spot" (
  "spot_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "name" varchar(100),
  "type" varchar(50) NOT NULL,
  "capacity" int NOT NULL,
  "price_per_night" int NOT NULL,
  "is_available" boolean DEFAULT true,
  "description" text,
  "updated_at" datetime,
  "row" int,
  "column" int,
  "rating" float
);

CREATE TABLE "booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "camping_id" int NOT NULL,
  "camping_spot_id" int NOT NULL,
  "arrival_date" date NOT NULL,
  "departure_date" date NOT NULL,
  "status" varchar(30),
  "qr_code" varchar(255)
);

CREATE TABLE "camping_photo" (
  "photo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "photo_url" varchar(255) NOT NULL,
  "caption" varchar(255),
  "uploaded_at" date
);

CREATE TABLE "entrance_gate" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "timestamp" datetime NOT NULL,
  "gate_id" int,
  "opening_time" time,
  "closing_time" time
);

CREATE TABLE "comment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "camping_id" int NOT NULL,
  "user_id" int NOT NULL,
  "parent_id" int,
  "rating" int,
  "comment" text,
  "upload_date" date
);

CREATE UNIQUE INDEX ON "user" ("email");

CREATE INDEX ON "camping_tag" ("camping_id");

CREATE UNIQUE INDEX ON "camping_tag" ("camping_id", "tag");

CREATE INDEX ON "camping_spot" ("camping_id");

CREATE UNIQUE INDEX ON "camping_spot" ("camping_id", "row", "column");

CREATE INDEX ON "booking" ("user_id");

CREATE INDEX ON "booking" ("camping_id");

CREATE INDEX ON "booking" ("camping_spot_id", "arrival_date", "departure_date");

CREATE INDEX ON "entrance_gate" ("camping_id", "timestamp");

CREATE INDEX ON "comment" ("camping_id");

CREATE INDEX ON "comment" ("user_id");

CREATE INDEX ON "comment" ("parent_id");

ALTER TABLE "user_guest" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "camping" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "camping" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");

ALTER TABLE "camping_tag" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "camping_spot" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("camping_spot_id") REFERENCES "camping_spot" ("spot_id");

ALTER TABLE "camping_photo" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "entrance_gate" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("camping_id") REFERENCES "camping" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("parent_id") REFERENCES "comment" ("id");

ALTER TABLE "camping" ADD FOREIGN KEY ("owner_last_name") REFERENCES "camping" ("id");
