CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" varchar,
  "birth_date" date,
  "phone_number" varchar
);

CREATE TABLE "location" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postcode" int,
  "county" varchar,
  "city" varchar,
  "street" varchar,
  "street_number" varchar
);

CREATE TABLE "campings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" int NOT NULL,
  "camping_name" varchar NOT NULL,
  "location_id" int NOT NULL,
  "description" text,
  "company_name" varchar,
  "tax_id" varchar,
  "billing_address" varchar
);

CREATE TABLE "camping_spot" (
  "spot_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campings_id" int NOT NULL,
  "name" varchar,
  "type" varchar,
  "capacity" int,
  "price_per_night" int,
  "is_available" boolean DEFAULT true,
  "description" text,
  "created_at" datetime,
  "updated_at" datetime,
  "row" int,
  "column" int,
  "rating" float,
  "tags" varchar
);

CREATE TABLE "camping_photo" (
  "photo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campings_id" int NOT NULL,
  "photo_url" varchar NOT NULL,
  "caption" varchar,
  "uploaded_at" date
);

CREATE TABLE "bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" int NOT NULL,
  "campings_id" int NOT NULL,
  "arrival_date" date NOT NULL,
  "departure_date" date NOT NULL,
  "status" varchar,
  "qr_code" varchar
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campings_id" int NOT NULL,
  "user_id" int NOT NULL,
  "parent_id" int,
  "rating" int,
  "comment" text,
  "upload_date" date
);

CREATE TABLE "user_guests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" int NOT NULL,
  "name" varchar,
  "place_of_birth" varchar,
  "date_of_birth" date,
  "gender" varchar,
  "citizenship" varchar,
  "mothers_birth_name" varchar,
  "ID" varchar,
  "passport_number" varchar,
  "visa" varchar,
  "resident_permit_number" varchar,
  "date_of_entry" date,
  "place_of_entry" varchar
);

CREATE TABLE "entrance_gate" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campings_id" int NOT NULL,
  "timestamp" datetime,
  "gate_id" int,
  "opening_time" time,
  "closing_time" time
);

ALTER TABLE "campings" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "campings" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");

ALTER TABLE "camping_spot" ADD FOREIGN KEY ("campings_id") REFERENCES "campings" ("id");

ALTER TABLE "camping_photo" ADD FOREIGN KEY ("campings_id") REFERENCES "campings" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("campings_id") REFERENCES "campings" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("campings_id") REFERENCES "campings" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("parent_id") REFERENCES "comments" ("id");

ALTER TABLE "user_guests" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "entrance_gate" ADD FOREIGN KEY ("campings_id") REFERENCES "campings" ("id");
